name = "Compress"
uuid = "80da91f2-9a6d-4152-9a2f-56ed2a57578d"
authors = ["Yisrael Haber <yisraelshacharhaber2@gmail.com>"]
version = "0.1.0"

[deps]
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
